name: Conditional Job Execution Example
on: [push]
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3     
      - name: Run a command
        run: echo "Job One is running"

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    if: success()
    steps:
      - name: Run only if job_one succeeds
        run: echo "Job Two is running because Job One succeeded"
      - name: Run this step only on the 'main' branch
        if: github.ref == 'refs/heads/main'
        run: echo "This step runs only on the main branch."
